// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyE6sKNwaBfcd9IstXgpoODv5hZIxFh0o',
    appId: '1:966465668140:web:d84b37c00f70cdd5adbd89',
    messagingSenderId: '966465668140',
    projectId: 'tasteclip-21160',
    authDomain: 'tasteclip-21160.firebaseapp.com',
    storageBucket: 'tasteclip-21160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66zQ2NmI8izLgVGFSfxJcCesN2Dcipo8',
    appId: '1:966465668140:android:3f6c63c080b9b5bfadbd89',
    messagingSenderId: '966465668140',
    projectId: 'tasteclip-21160',
    storageBucket: 'tasteclip-21160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAzT1EZMqVg2YsXcnilB2P7ZX7DvwobOU',
    appId: '1:966465668140:ios:1df7b4625b2bbc77adbd89',
    messagingSenderId: '966465668140',
    projectId: 'tasteclip-21160',
    storageBucket: 'tasteclip-21160.appspot.com',
    iosBundleId: 'com.example.tasteclip',
  );
}
