import 'chat_controller.dart';

final List<String> pakistaniCities = [
  'Islamabad',
  'Okara',
  'Khanewal',
  'Sahiwal',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Multan',
  'Gujranwala',
  'Sialkot',
  'Bahawalpur',
  'Sargodha',
  'Rahim Yar Khan',
  'Karachi',
  'Hyderabad',
  'Sukkur',
  'Larkana',
  'Nawabshah',
  'Peshawar',
  'Abbottabad',
  'Mardan',
  'Swat',
  'Bannu',
  'Quetta',
  'Gwadar',
  'Khuzdar',
  'Turbat',
  'Sibi',
  'Gilgit',
  'Skardu',
  'Muzaffarabad',
  'Mirpur',
];

final List<String> foodCategories = [
  'Biryani',
  'BBQ',
  'Karahi',
  'Pulao',
  'Haleem',
  'Nihari',
  'Fast Food',
  'Chinese',
];

final Map<String, Map<String, List<Restaurant>>> recommendations = {
  'Islamabad': {
    'Biryani': [
      Restaurant(
        name: 'Karachi Biryani and Restaurant',
        specialty: 'Biryani',
        location: 'F-7 Markaz',
        highlight: 'Spicy Biryani',
        rating: 4.2,
      ),
      Restaurant(
        name: 'Biryani Spot',
        specialty: 'Biryani',
        location: 'MPCHS E 11/1 E-11',
        highlight: 'Affordable & tasty',
        rating: 4.9,
      ),
      Restaurant(
        name: 'Tandoori Restaurant',
        specialty: 'Biryani',
        location: 'Khursheed Market, F-10',
        highlight: 'Special masala',
        rating: 4.3,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'Bar B.Q. Tonight',
        specialty: 'BBQ',
        location: 'Blue Area',
        highlight: 'Smokey flavor',
        rating: 4.1,
      ),
      Restaurant(
        name: 'Hanif Rajput RoofTop Grill',
        specialty: 'BBQ',
        location: 'Markaz G-9',
        highlight: 'Grilled to perfection',
        rating: 4.4,
      ),
      Restaurant(
        name: '1969 Restaurant',
        specialty: 'BBQ',
        location: 'Garden Ave, Shakarpairan',
        highlight: 'Smokey flavor',
        rating: 4.2,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'Markaz, F-10',
        highlight: 'Desi ghee karahi',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Tandoori Restaurant',
        specialty: 'Karahi',
        location: 'Khursheed Market, F-10',
        highlight: 'Special masala',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Khyber Dodai',
        specialty: 'Karahi',
        location: 'Markaz F-6',
        highlight: 'Tender meat',
        rating: 4.1,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Siddique Bannu Beef Pulao & Painda',
        specialty: 'Pulao',
        location: 'Markaz G-9',
        highlight: 'Famous pulao',
        rating: 4.2,
      ),
      Restaurant(
        name: 'Savour Foods',
        specialty: 'Pulao',
        location: 'Fortune Plaza, Blue Area',
        highlight: 'Delicious rice',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Mian Jee Murgh Pulao And Restaurant',
        specialty: 'Pulao',
        location: 'Ghauri Town',
        highlight: 'Chicken pulao',
        rating: 4.0,
      ),
    ],
    'Haleem': [
      Restaurant(
        name: 'Haleem Ghar',
        specialty: 'Haleem',
        location: 'Ginza Center, Jinnah Ave, Blue Area,',
        highlight: 'Authentic recipe',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Mrs.Zaidi Haleem',
        specialty: 'Haleem',
        location: 'federation housing society, Sector O-9 Doctors CHS',
        highlight: 'Rich taste',
        rating: 4.9,
      ),
      Restaurant(
        name: '1969 Restaurant',
        specialty: 'Haleem',
        location: 'Garden Ave, Shakarpairan',
        highlight: 'Spicy delight',
        rating: 4.2,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Muhammadi Nahari House',
        specialty: 'Nihari',
        location: 'Markaz I-10',
        highlight: 'Desi style',
        rating: 4.1,
      ),
      Restaurant(
        name: 'Dilli Darwaza',
        specialty: 'Nihari',
        location: 'F 8/1 Allahwali Market',
        highlight: 'Slow-cooked beef',
        rating: 4.2,
      ),
      Restaurant(
        name: 'Pakistan Restaurant',
        specialty: 'Nihari',
        location: 'Golra More, Main Peshawar Rd',
        highlight: 'With bone marrow',
        rating: 4.4,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Yum Chinese & Thai',
        specialty: 'Chinese',
        location: 'Street 16, F-7/2',
        highlight: 'Authentic Chinese',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Yangtze Chinese Cuisine',
        specialty: 'Chinese',
        location: 'Markaz G-11',
        highlight: 'Modern Chinese',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Asian Wok',
        specialty: 'Chinese',
        location: 'F 6/1 Blue Area',
        highlight: 'Classic menu',
        rating: 4.5,
      ),
    ],
  },
  'Okara': {
    'Biryani': [
      Restaurant(
        name: 'Kababish Restaurant',
        specialty: 'Biryani',
        location: 'Benazir Rd, Imran Akram Villas',
        highlight: '',
        rating: 4.0,
      ),
      Restaurant(
        name: 'Rehmani Barbeque',
        specialty: 'Biryani',
        location: 'Depalpur Rd, Block C',
        highlight: '',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Pak Rohani Restaurant ',
        specialty: 'Biryani',
        location: 'Benazir Rd, Imran Akram Villas',
        highlight: '',
        rating: 4.0,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'Depalpur Rd, Block C',
        specialty: 'BBQ',
        location: 'Depalpur Rd, Block C',
        highlight: '',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Makkah-tul-barakat Restaurant',
        specialty: 'BBQ',
        location: 'Main Government Colony Rd',
        highlight: '',
        rating: 4.9,
      ),
      Restaurant(
        name: 'Ali Barbeque',
        specialty: 'BBQ',
        location: 'Faisalabad Road, Faisal Colony',
        highlight: '',
        rating: 4.6,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Kababish Restaurant',
        specialty: 'Karahi',
        location: 'Benazir Rd, Imran Akram Villas',
        highlight: '',
        rating: 4.0,
      ),
      Restaurant(
        name: 'Rehmani Barbeque',
        specialty: 'Karahi',
        location: 'Depalpur Rd, Block C Okara',
        highlight: '',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'Main G.T Road',
        highlight: '',
        rating: 4.3,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'The Khan Ji Banu Beef Pulao and tikka house',
        specialty: 'Pulao',
        location: 'Katchery Bazar Rd',
        highlight: '',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Rehmani Barbeque',
        specialty: 'Pulao',
        location: 'Depalpur Rd, Block C',
        highlight: '',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Food Garden',
        specialty: 'Pulao',
        location: 'Grand Trunk Rd, Renala Khurd',
        highlight: '',
        rating: 4.3,
      ),
    ],
    'Haleem': [
      Restaurant(
        name: 'Royal Sheesh Mahal Family Restaurant',
        specialty: 'Haleem',
        location: 'RGM3+GMQ, Okara',
        highlight: '',
        rating: 4.1,
      ),
      Restaurant(
        name: 'Pak Rohani Restaurant',
        specialty: 'Haleem',
        location: 'Benazir Rd, Imran Akram Villas',
        highlight: '',
        rating: 4.0,
      )
    ],
  },
  'Khanewal': {
    'Biryani': [
      Restaurant(
        name: 'Karachi Hot N Spicy Bar B.Q',
        specialty: 'Biryani',
        location: 'Multan Bypass, near Daha Chowk',
        highlight:
            'Variety of biryani options including BBQ Biryani Leg and Royal Sindhi Chicken Biryani Handi',
        rating: 4.0,
      ),
      Restaurant(
        name: 'Punjab Restaurant & Pakwan Center',
        specialty: 'Biryani',
        location: 'Peoples Colony, College Stop, Khanewal',
        highlight: 'Offers traditional biryani with authentic flavors',
        rating: 3.5,
      ),
      Restaurant(
        name: 'Pak China Restaurant',
        specialty: 'Biryani',
        location: 'Ahl e Hadees Chowk Near Qadri Hospital Khanewal',
        highlight: 'Serves Chicken Masala Rice and other biryani varieties',
        rating: 3.8,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'Karachi Hot N Spicy Bar B.Q',
        specialty: 'BBQ',
        location: 'Multan Bypass, near Daha Chowk',
        highlight:
            'Extensive BBQ menu featuring Grilled Chicken Seekh Kabab and Special Chicken Bihari Boti',
        rating: 4.0,
      ),
      Restaurant(
        name: 'Bismillah Restaurant & BBQ',
        specialty: 'BBQ',
        location:
            'Multan-Kabirwala Rd, Purana Larri Adda, Nawan Shehar Gharbi, Kabirwala',
        highlight: 'Known for its flavorful BBQ dishes and fast food options',
        rating: 4.2,
      ),
      Restaurant(
        name: 'Iqbal Jan Restaurant & B.B.Q. Tulamba',
        specialty: 'BBQ',
        location: 'G6GM+77C, Tulamba, Khanewal',
        highlight: 'Offers a variety of BBQ dishes with traditional taste',
        rating: 4.0,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Karachi Hot N Spicy Bar B.Q',
        specialty: 'Karahi',
        location: 'Multan Bypass, near Daha Chowk',
        highlight:
            'Offers Chicken Karahi, Mutton Karahi, and Special Tawa Chicken Karahi',
        rating: 4.0,
      ),
      Restaurant(
        name: 'Punjab Restaurant & Pakwan Center',
        specialty: 'Karahi',
        location: 'Peoples Colony, College Stop, Khanewal',
        highlight: 'Serves traditional Karahi and Handi dishes',
        rating: 3.5,
      ),
      Restaurant(
        name: 'Pak China Restaurant',
        specialty: 'Karahi',
        location: 'Ahl e Hadees Chowk Near Qadri Hospital Khanewal',
        highlight: 'Offers Chicken Karahi and Chicken White Karahi',
        rating: 3.8,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Punjab Restaurant & Pakwan Center',
        specialty: 'Pulao',
        location: 'Peoples Colony, College Stop, Khanewal',
        highlight:
            'Known for traditional Murgh Pulao and a variety of pakwan dishes',
        rating: 3.5,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Lahori Naan Shop',
        specialty: 'Nihari',
        location: 'Near Old Sabzi Mandi Plots',
        highlight:
            'Specializes in Maghaz Nihari, Nalli Nihari, and Special Maghaz Nalli Nihari',
        rating: 4.0,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Pak China Restaurant',
        specialty: 'Chinese',
        location: 'Ahl e Hadees Chowk Near Qadri Hospital Khanewal',
        highlight:
            'Offers a range of Chinese dishes including Chicken Manchurian and Chicken Chili Dry',
        rating: 3.8,
      ),
      Restaurant(
        name: 'Beba\'s Kitchen',
        specialty: 'Chinese',
        location:
            'In front of Qudas Masjid, Main Bypass Road, Jinnah Colony, Jahanian, Khanewal',
        highlight: 'Known for its Chinese cuisine with a local twist',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Tasty Food\'s',
        specialty: 'Chinese',
        location: 'Muslim League Chowk, Liaquat Road, Mian Channu, Khanewal',
        highlight: 'Offers a variety of Chinese dishes with authentic flavors',
        rating: 4.0,
      ),
    ],
  },
  'Sahiwal': {
    'Biryani': [
      Restaurant(
        name: 'Karachi Naseeb Biryani',
        specialty: 'Biryani',
        location: 'Sahiwal',
        highlight:
            'Offers a variety of biryani options including Chicken Biryani and Special Biryani Deals',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Dua Biryani',
        specialty: 'Biryani',
        location: 'Sahiwal',
        highlight: 'Known for its flavorful and aromatic biryani',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Sardar Yakhni Pulao & Biryani',
        specialty: 'Biryani',
        location: 'Sahiwal',
        highlight: 'Serves traditional desi biryani with rich flavors',
        rating: 4.3,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'Dera Sultan Bar B Q & Restaurant',
        specialty: 'BBQ',
        location: 'Lahore-Multan Road, Harappa Bypass, near Hamza CNG, Sahiwal',
        highlight: 'Offers a variety of BBQ dishes with authentic taste',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Shahbaz Tikka',
        specialty: 'BBQ',
        location: 'Bypass Arif Wala Chowk, Sahiwal',
        highlight: 'Known for its delicious BBQ items and quick service',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Al-Hamad Grilled Fish and Bar BBQ',
        specialty: 'BBQ',
        location: 'Bilal Colony Road, Bhutto Nagar, Sahiwal',
        highlight: 'Offers grilled fish and a variety of BBQ dishes',
        rating: 4.4,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Bulbul Hotel',
        specialty: 'Karahi',
        location: 'Sahiwal',
        highlight: 'Famous for its Makhan Chicken Karahi with rich flavors',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Chatkhara Original',
        specialty: 'Karahi',
        location: 'Sahiwal',
        highlight: 'Offers a variety of karahi dishes with traditional taste',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Ajwa Garden Restaurant & Marriage Hall',
        specialty: 'Karahi',
        location: 'Multan-Lahore Road, Main Bypass, Sahiwal',
        highlight: 'Known for its Mutton Shinwari Karahi and spacious dining',
        rating: 4.4,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Bannu Pulao',
        specialty: 'Pulao',
        location: 'Sahiwal',
        highlight: 'Serves authentic Bannu-style beef pulao with rich flavors',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Al Sheikh Murgh Pulao',
        specialty: 'Pulao',
        location: 'Sahiwal',
        highlight: 'Offers special Murgh Pulao and other traditional dishes',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Karachi Naseeb Biryani',
        specialty: 'Pulao',
        location: 'Sahiwal',
        highlight:
            'Provides a variety of pulao options including Beef and Chicken Pulao',
        rating: 4.7,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Khyber Shinwari Restaurant & Tikka House',
        specialty: 'Nihari',
        location: 'Sahiwal',
        highlight: 'Known for its flavorful Nihari and Shinwari dishes',
        rating: 4.5,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'New Chinese Club',
        specialty: 'Chinese',
        location: 'Sahiwal',
        highlight: 'Offers a variety of Chinese dishes with authentic taste',
        rating: 4.9,
      ),
      Restaurant(
        name: 'Anaya Chinese',
        specialty: 'Chinese',
        location: 'Sahiwal',
        highlight:
            'Known for its premium Chinese cuisine and fine dining experience',
        rating: 4.8,
      ),
      Restaurant(
        name: 'Roti Shoti Family Restaurant & Events Organizer',
        specialty: 'Chinese',
        location: 'Sahiwal',
        highlight:
            'Provides a range of Chinese dishes in a family-friendly environment',
        rating: 5.0,
      ),
    ],
  },
  'Lahore': {
    'Biryani': [
      Restaurant(
        name: 'Karachi Biryani House',
        specialty: 'Biryani',
        location: 'Near Liberty Market, Gulberg III',
        highlight: 'Authentic Karachi-style biryani with a spicy kick',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Food Street, Gawalmandi',
        specialty: 'Biryani',
        location: 'Gawalmandi, Lahore',
        highlight: 'Traditional biryani served in a historic setting',
        rating: 4.2,
      ),
      Restaurant(
        name: 'Tandoor Restaurant',
        specialty: 'Biryani',
        location: 'Near Mall Road, Lahore',
        highlight: 'Known for its flavorful biryani and tandoori dishes',
        rating: 4.3,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'BBQ Tonight',
        specialty: 'BBQ',
        location: 'Mian Mehmood Ali Kasoori Rd, Gulberg III',
        highlight:
            'Offers a wide variety of BBQ items including mutton ribs and chicken tikka',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Baba Jamal Tikka House',
        specialty: 'BBQ',
        location: 'Tufail Road, Cantt Lahore',
        highlight:
            'Famous for its beef tikka, marinated and slow-grilled over coals',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Grill n’ Bake',
        specialty: 'BBQ',
        location: '214-A, Block-L Model Town, Lahore',
        highlight: 'Specializes in Kasturi Boti and lamb chops',
        rating: 4.6,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'McLeod Rd, Gawalmandi',
        highlight:
            'Renowned for its lamb and chicken karahi cooked in desi ghee',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Khan Baba',
        specialty: 'Karahi',
        location: 'Near Liberty Market, Gulberg III',
        highlight:
            'Offers a variety of karahi dishes with a focus on hygiene and quality',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Chai Wala',
        specialty: 'Karahi',
        location: 'Near Mall Road, Lahore',
        highlight: 'Known for its unique blend of karahi and tea offerings',
        rating: 4.3,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Savour Foods',
        specialty: 'Pulao',
        location: 'Near Liberty Market, Gulberg III',
        highlight: 'Famous for its chicken pulao and raita',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Chai Wala',
        specialty: 'Pulao',
        location: 'Near Mall Road, Lahore',
        highlight:
            'Offers a delightful chicken pulao with a side of traditional chutney',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Tandoor Restaurant',
        specialty: 'Pulao',
        location: 'Near Mall Road, Lahore',
        highlight: 'Known for its flavorful pulao and tandoori dishes',
        rating: 4.3,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Waris Nihari House',
        specialty: 'Nihari',
        location: '7 Abkari Rd, New Anarkali',
        highlight:
            'Offers a variety of nihari options including beef, mutton, and chicken',
        rating: 4.8,
      ),
      Restaurant(
        name: 'Muhammadi Nihari House',
        specialty: 'Nihari',
        location: 'Bahawalpur Rd, Lahore',
        highlight: 'Known for its rich and flavorful nihari',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Haji Sahib Nihari Waly',
        specialty: 'Nihari',
        location: 'Lohari Gate, Moti Bazaar',
        highlight: 'Serves traditional nihari with a variety of options',
        rating: 4.6,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Jade Cafe and Chinatown',
        specialty: 'Chinese',
        location: 'Gulberg III, off MM Alam Road',
        highlight:
            'Offers authentic Chinese cuisine with a rooftop dining experience',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Bamboo Union',
        specialty: 'Chinese',
        location: 'Gulberg III, Lahore',
        highlight:
            'Known for its Pan-Asian dishes including tamarind fish and chicken dumplings',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Monal Lahore',
        specialty: 'Chinese',
        location: 'Liberty Chowk, Gulberg III',
        highlight: 'Offers a variety of Chinese dishes with a scenic view',
        rating: 4.4,
      ),
    ],
  },
  'Faisalabad': {
    'Biryani': [
      Restaurant(
        name: 'Biryani King',
        specialty: 'Biryani',
        location: 'Jaranwala Road, Faisalabad',
        highlight: 'Famous for its spicy biryani with a variety of meats',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Khana Biryani',
        specialty: 'Biryani',
        location: 'Sargodha Road, Faisalabad',
        highlight: 'Delicious chicken biryani served with raita and salad',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Khan Biryani House',
        specialty: 'Biryani',
        location: 'Millat Road, Faisalabad',
        highlight: 'Known for its traditional biryani and special masala mix',
        rating: 4.2,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'BBQ Hut',
        specialty: 'BBQ',
        location: 'Abu Bakar Road, Faisalabad',
        highlight: 'Serves delicious chicken and mutton BBQ with smoky flavor',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Grill House',
        specialty: 'BBQ',
        location: 'Satyana Road, Faisalabad',
        highlight: 'Specializes in grilled chicken and lamb chops',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Bashir BBQ',
        specialty: 'BBQ',
        location: 'Sitara Market, Faisalabad',
        highlight: 'Famous for its tender BBQ meats and unique marinades',
        rating: 4.3,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'Millat Road, Faisalabad',
        highlight: 'Renowned for its tender chicken and mutton karahi',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Shahi Karahi',
        specialty: 'Karahi',
        location: 'Mitcham Road, Faisalabad',
        highlight: 'Offers a variety of karahi options with rich flavors',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Karahi King',
        specialty: 'Karahi',
        location: 'Faisalabad Road, Faisalabad',
        highlight:
            'Specializes in chicken karahi cooked in traditional desi ghee',
        rating: 4.6,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Savour Foods',
        specialty: 'Pulao',
        location: 'Satyana Road, Faisalabad',
        highlight: 'Famous for its chicken pulao and delicious raita',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Food Street',
        specialty: 'Pulao',
        location: 'Khayaban-e-Faisal, Faisalabad',
        highlight: 'Known for its flavorful pulao and kebabs',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Mian Jee Murgh Pulao',
        specialty: 'Pulao',
        location: 'Canal Road, Faisalabad',
        highlight: 'Chicken pulao with a unique blend of spices',
        rating: 4.4,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Waris Nihari House',
        specialty: 'Nihari',
        location: 'Satyana Road, Faisalabad',
        highlight: 'Famous for its rich, slow-cooked nihari',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Muhammadi Nihari House',
        specialty: 'Nihari',
        location: 'Lahore Road, Faisalabad',
        highlight: 'Known for its flavorful nihari cooked with a secret masala',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Circular Road, Faisalabad',
        highlight: 'Offers tender beef nihari with bone marrow',
        rating: 4.5,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Chai Wala',
        specialty: 'Chinese',
        location: 'Jaranwala Road, Faisalabad',
        highlight: 'Offers a variety of authentic Chinese dishes',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Dragon House',
        specialty: 'Chinese',
        location: 'Satyana Road, Faisalabad',
        highlight: 'Specializes in Chinese-style chicken, rice, and noodles',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Beijing Express',
        specialty: 'Chinese',
        location: 'Millat Road, Faisalabad',
        highlight: 'Known for its traditional Chinese menu with a modern twist',
        rating: 4.5,
      ),
    ],
  },
  'Rawalpindi': {
    'Biryani': [
      Restaurant(
        name: 'Chai Wala',
        specialty: 'Biryani',
        location: 'Mouza Jand, Rawalpindi',
        highlight: 'Famous for its spicy chicken and mutton biryani',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Tandoor Restaurant',
        specialty: 'Biryani',
        location: 'Saddar, Rawalpindi',
        highlight: 'Authentic Biryani with flavorsome spices',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Biryani Express',
        specialty: 'Biryani',
        location: 'Murree Road, Rawalpindi',
        highlight: 'Known for its rich masala biryani and good portion size',
        rating: 4.2,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'BBQ Tonight',
        specialty: 'BBQ',
        location: 'The Mall, Rawalpindi',
        highlight: 'Known for its smoky grilled chicken and mutton',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Shahjehan Grill',
        specialty: 'BBQ',
        location: 'Jinnah Park, Rawalpindi',
        highlight: 'Offers a variety of grilled meat and BBQ dishes',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Haveli Restaurant',
        specialty: 'BBQ',
        location: 'Saddar, Rawalpindi',
        highlight: 'Renowned for its BBQ platter and delicious sides',
        rating: 4.5,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'Rawalpindi Saddar',
        highlight: 'Specializes in tender chicken karahi cooked in desi ghee',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Tandoor Restaurant',
        specialty: 'Karahi',
        location: 'Saddar, Rawalpindi',
        highlight: 'Famous for its traditional karahi and spices',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Dera Restaurant',
        specialty: 'Karahi',
        location: 'Murree Road, Rawalpindi',
        highlight: 'Offers spicy and flavorful karahi dishes',
        rating: 4.3,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Bismillah Pulao',
        specialty: 'Pulao',
        location: 'Committee Chowk, Rawalpindi',
        highlight: 'Specializes in flavorful beef and chicken pulao',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Siddique Bannu Beef Pulao',
        specialty: 'Pulao',
        location: 'Murree Road, Rawalpindi',
        highlight: 'Known for its flavorful chicken and beef pulao',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Food Street Rawalpindi',
        specialty: 'Pulao',
        location: 'Rawalpindi Cantonment',
        highlight: 'Delicious rice dishes with BBQ items',
        rating: 4.3,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Waris Nihari',
        specialty: 'Nihari',
        location: 'Raja Bazaar, Rawalpindi',
        highlight: 'Renowned for its rich beef nihari',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Liaquat Road, Rawalpindi',
        highlight: 'Known for its slow-cooked nihari with bone marrow',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Peshawar Nihari House',
        specialty: 'Nihari',
        location: 'Murree Road, Rawalpindi',
        highlight: 'Specializes in authentic Peshawari-style nihari',
        rating: 4.5,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Dragon Chinese',
        specialty: 'Chinese',
        location: 'Saddar, Rawalpindi',
        highlight: 'Offers classic Chinese food with a local twist',
        rating: 4.4,
      ),
      Restaurant(
        name: 'The Chinese Restaurant',
        specialty: 'Chinese',
        location: 'Mouza Jand, Rawalpindi',
        highlight: 'Known for its delicious chicken and beef stir-fry dishes',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Jiangnan Chinese Restaurant',
        specialty: 'Chinese',
        location: 'Murree Road, Rawalpindi',
        highlight: 'Authentic Chinese flavors with a great ambiance',
        rating: 4.3,
      ),
    ],
  },
  'Multan': {
    'Biryani': [
      Restaurant(
        name: 'Karachi Biryani House',
        specialty: 'Biryani',
        location: 'Hussain Agahi Bazaar, Multan',
        highlight: 'Spicy chicken biryani and great portion size',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Biryani Wala',
        specialty: 'Biryani',
        location: 'Qasim Bela, Multan',
        highlight: 'Fluffy rice with tender meat',
        rating: 4.2,
      ),
      Restaurant(
        name: 'Tandoor Restaurant',
        specialty: 'Biryani',
        location: 'City Chowk, Multan',
        highlight: 'Authentic biryani with delicious spices',
        rating: 4.3,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'Shah Ji BBQ',
        specialty: 'BBQ',
        location: 'Chungi No. 9, Multan',
        highlight: 'Known for its smoky grilled chicken and mutton',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Haveli BBQ',
        specialty: 'BBQ',
        location: 'Khalid Market, Multan',
        highlight: 'Grilled to perfection with great flavor',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Al-Madina BBQ',
        specialty: 'BBQ',
        location: 'Nawan Shehr, Multan',
        highlight: 'Specializes in grilled kebabs and BBQ chicken',
        rating: 4.3,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'Bosan Road, Multan',
        highlight: 'Famous for its desi ghee karahi',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Dera Restaurant',
        specialty: 'Karahi',
        location: 'Lodhi Colony, Multan',
        highlight: 'Specializes in spicy chicken and mutton karahi',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Shahi Karahi',
        specialty: 'Karahi',
        location: 'Qasim Bela, Multan',
        highlight: 'Rich and spicy karahi with tender meat',
        rating: 4.5,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Bismillah Pulao',
        specialty: 'Pulao',
        location: 'Bosan Road, Multan',
        highlight: 'Flavorsome pulao with delicious meats',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Siddique Bannu Beef Pulao',
        specialty: 'Pulao',
        location: 'Shah Rukn-e-Alam, Multan',
        highlight: 'Famous for its beef pulao',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Food Street Multan',
        specialty: 'Pulao',
        location: 'Hussain Agahi, Multan',
        highlight: 'Rice dishes served with BBQ items',
        rating: 4.3,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Waris Nihari',
        specialty: 'Nihari',
        location: 'Nawan Shehr, Multan',
        highlight: 'Renowned for its rich beef nihari',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Peshawar Nihari House',
        specialty: 'Nihari',
        location: 'Raja Bazaar, Multan',
        highlight: 'Known for its slow-cooked nihari with bone marrow',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Lodhi Colony, Multan',
        highlight: 'Traditional nihari with spices',
        rating: 4.4,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Yum Chinese Restaurant',
        specialty: 'Chinese',
        location: 'City Chowk, Multan',
        highlight: 'Authentic Chinese cuisine with a variety of options',
        rating: 4.3,
      ),
      Restaurant(
        name: 'Great Wall Chinese',
        specialty: 'Chinese',
        location: 'Shah Rukn-e-Alam, Multan',
        highlight: 'Known for its fresh and tasty Chinese food',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Dragon Palace',
        specialty: 'Chinese',
        location: 'Bosan Road, Multan',
        highlight: 'Offers traditional Chinese with a local twist',
        rating: 4.4,
      ),
    ],
  },
  'Karachi': {
    'Biryani': [
      Restaurant(
        name: 'Karachi Biryani House',
        specialty: 'Biryani',
        location: 'Korangi',
        highlight: 'Spicy and flavorful biryani',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Biryani of the Seas',
        specialty: 'Biryani',
        location: 'Clifton',
        highlight: 'Seafood biryani with fresh fish',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Student Biryani',
        specialty: 'Biryani',
        location: 'Multiple locations',
        highlight: 'Famous for its unique biryani recipe',
        rating: 4.5,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'BBQ Tonight',
        specialty: 'BBQ',
        location: 'Karachi Marina Club',
        highlight: 'Smoky and tender BBQ meats',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Bar B.Q. Tonight',
        specialty: 'BBQ',
        location: 'Clifton',
        highlight: 'Grilled kebabs and delicious BBQ',
        rating: 4.5,
      ),
      Restaurant(
        name: 'The BBQ Tonight',
        specialty: 'BBQ',
        location: 'Korangi',
        highlight: 'Affordable and juicy BBQ',
        rating: 4.3,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Butt Karahi',
        specialty: 'Karahi',
        location: 'Karachi Saddar',
        highlight: 'Desi ghee karahi with tender meat',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Shahi Karahi',
        specialty: 'Karahi',
        location: 'Korangi',
        highlight: 'Spicy and flavorful karahi',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Zaiqa Karahi',
        specialty: 'Karahi',
        location: 'Nazimabad',
        highlight: 'Famous for its spicy chicken karahi',
        rating: 4.5,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Bismillah Pulao',
        specialty: 'Pulao',
        location: 'Shahrah-e-Faisal',
        highlight: 'Delicious and well-seasoned pulao',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Karachi Pulao House',
        specialty: 'Pulao',
        location: 'Korangi',
        highlight: 'Fluffy rice with savory beef and chicken',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Siddique Bannu Beef Pulao',
        specialty: 'Pulao',
        location: 'Karachi Saddar',
        highlight: 'Special beef pulao',
        rating: 4.4,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Waris Nihari',
        specialty: 'Nihari',
        location: 'Saddar',
        highlight: 'Traditional nihari with bone marrow',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Peshawar Nihari House',
        specialty: 'Nihari',
        location: 'Saddar',
        highlight: 'Slow-cooked nihari with rich flavor',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Korangi',
        highlight: 'Nihari cooked in desi style',
        rating: 4.4,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Yum Chinese & Thai',
        specialty: 'Chinese',
        location: 'Clifton',
        highlight: 'Authentic Chinese with Thai flavors',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Yangtze Chinese Cuisine',
        specialty: 'Chinese',
        location: 'Korangi',
        highlight: 'Traditional Chinese dishes with a modern twist',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Chai Wala',
        specialty: 'Chinese',
        location: 'Karachi Saddar',
        highlight: 'Best Chinese fast food',
        rating: 4.4,
      ),
    ],
  },
  'Hyderabad': {
    'Biryani': [
      Restaurant(
        name: 'Shadab Biryani',
        specialty: 'Biryani',
        location: 'Saddar, Hyderabad',
        highlight: 'Spicy and flavorful biryani',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Student Biryani',
        specialty: 'Biryani',
        location: 'Market Road, Hyderabad',
        highlight: 'Unique blend of spices and tender meat',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Ameer Biryani',
        specialty: 'Biryani',
        location: 'Hali Road, Hyderabad',
        highlight: 'Affordable and delicious biryani',
        rating: 4.4,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'BBQ Tonight',
        specialty: 'BBQ',
        location: 'Hyderabad Saddar',
        highlight: 'Famous grilled meats and kebabs',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Zaiqa BBQ',
        specialty: 'BBQ',
        location: 'Ameer Ali Market, Hyderabad',
        highlight: 'Juicy grilled kebabs and BBQ specialties',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Shahi BBQ',
        specialty: 'BBQ',
        location: 'Liaquat Market, Hyderabad',
        highlight: 'Grilled meats with great smoky flavor',
        rating: 4.4,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Khawaja Karahi',
        specialty: 'Karahi',
        location: 'Saddar, Hyderabad',
        highlight: 'Spicy chicken karahi cooked in desi ghee',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Nazeer Karahi',
        specialty: 'Karahi',
        location: 'Rani Bagh, Hyderabad',
        highlight: 'Tender meat and spicy flavors',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Dera Karahi',
        specialty: 'Karahi',
        location: 'Hali Road, Hyderabad',
        highlight: 'Special karahi with rich spices',
        rating: 4.5,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Bismillah Pulao',
        specialty: 'Pulao',
        location: 'Saddar, Hyderabad',
        highlight: 'Delicious and flavorful rice with meat',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Hyderabad Pulao House',
        specialty: 'Pulao',
        location: 'Qasimabad, Hyderabad',
        highlight: 'Famous pulao with tender chicken and beef',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Shahi Pulao',
        specialty: 'Pulao',
        location: 'Hali Road, Hyderabad',
        highlight: 'Fluffy rice with special spices',
        rating: 4.3,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Liaquat Market, Hyderabad',
        highlight: 'Traditional nihari with bone marrow',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Waris Nihari',
        specialty: 'Nihari',
        location: 'Saddar, Hyderabad',
        highlight: 'Slow-cooked beef nihari',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Peshawar Nihari House',
        specialty: 'Nihari',
        location: 'Qasimabad, Hyderabad',
        highlight: 'Rich and spicy nihari',
        rating: 4.4,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Chai Wala Chinese',
        specialty: 'Chinese',
        location: 'Saddar, Hyderabad',
        highlight: 'Delicious Chinese fast food',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Yum Chinese & Thai',
        specialty: 'Chinese',
        location: 'Market Road, Hyderabad',
        highlight: 'Authentic Chinese and Thai dishes',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Red Dragon Chinese',
        specialty: 'Chinese',
        location: 'Rani Bagh, Hyderabad',
        highlight: 'Special Chinese food with a local twist',
        rating: 4.6,
      ),
    ],
  },
  'Peshawar': {
    'Biryani': [
      Restaurant(
        name: 'Bismillah Biryani',
        specialty: 'Biryani',
        location: 'University Road, Peshawar',
        highlight: 'Famous for flavorful biryani',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Peshawar Biryani House',
        specialty: 'Biryani',
        location: 'Khyber Bazaar, Peshawar',
        highlight: 'Unique taste of traditional biryani',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Tandoor Biryani',
        specialty: 'Biryani',
        location: 'Hayatabad, Peshawar',
        highlight: 'Spicy and aromatic biryani',
        rating: 4.4,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'Chapli Kebab House',
        specialty: 'BBQ',
        location: 'Peshawar Saddar',
        highlight: 'Traditional Chapli Kebabs with a smoky flavor',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Khyber BBQ',
        specialty: 'BBQ',
        location: 'Khyber Road, Peshawar',
        highlight: 'Delicious BBQ kebabs and grilled meats',
        rating: 4.6,
      ),
      Restaurant(
        name: 'The BBQ Lounge',
        specialty: 'BBQ',
        location: 'University Road, Peshawar',
        highlight: 'Smoky grilled BBQ and tender meats',
        rating: 4.5,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Peshawar Karahi',
        specialty: 'Karahi',
        location: 'Saddar, Peshawar',
        highlight: 'Spicy and flavorful karahi dishes',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Shahi Karahi',
        specialty: 'Karahi',
        location: 'Gulberg, Peshawar',
        highlight: 'Famous for spicy chicken karahi',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Waris Karahi',
        specialty: 'Karahi',
        location: 'Khyber Bazaar, Peshawar',
        highlight: 'Tender meat cooked in desi ghee',
        rating: 4.4,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Pulao Corner',
        specialty: 'Pulao',
        location: 'University Road, Peshawar',
        highlight: 'Special beef and chicken pulao',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Khyber Pulao',
        specialty: 'Pulao',
        location: 'Saddar, Peshawar',
        highlight: 'Flavorful pulao with tender meat',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Shahi Pulao',
        specialty: 'Pulao',
        location: 'Cantt, Peshawar',
        highlight: 'Rice cooked with aromatic spices',
        rating: 4.3,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Saddar, Peshawar',
        highlight: 'Authentic nihari with tender meat',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Waris Nihari',
        specialty: 'Nihari',
        location: 'University Road, Peshawar',
        highlight: 'Rich and flavorful nihari',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Peshawar Nihari House',
        specialty: 'Nihari',
        location: 'Cantt, Peshawar',
        highlight: 'Traditional nihari cooked with spices',
        rating: 4.5,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Yum Chinese',
        specialty: 'Chinese',
        location: 'Saddar, Peshawar',
        highlight: 'Authentic Chinese flavors with a local twist',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Red Dragon Chinese',
        specialty: 'Chinese',
        location: 'University Road, Peshawar',
        highlight: 'Delicious Chinese dishes with bold spices',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Beijing Chinese',
        specialty: 'Chinese',
        location: 'Khyber Bazaar, Peshawar',
        highlight: 'Specialized in traditional Chinese cuisine',
        rating: 4.6,
      ),
    ],
  },
  'Quetta': {
    'Biryani': [
      Restaurant(
        name: 'Bismillah Biryani',
        specialty: 'Biryani',
        location: 'Saddar, Quetta',
        highlight: 'Flavorful and spicy biryani',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Quetta Biryani House',
        specialty: 'Biryani',
        location: 'Jinnah Road, Quetta',
        highlight: 'Traditional biryani with a unique twist',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Student Biryani',
        specialty: 'Biryani',
        location: 'Quetta Cantt',
        highlight: 'Famous for its aromatic and tender biryani',
        rating: 4.4,
      ),
    ],
    'BBQ': [
      Restaurant(
        name: 'BBQ House',
        specialty: 'BBQ',
        location: 'Saddar, Quetta',
        highlight: 'Smoky grilled meats and kebabs',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Al-Madina BBQ',
        specialty: 'BBQ',
        location: 'Jinnah Road, Quetta',
        highlight: 'Authentic BBQ and grilled meats',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Khyber BBQ',
        specialty: 'BBQ',
        location: 'Quetta Cantt',
        highlight: 'Delicious BBQ with local spices',
        rating: 4.4,
      ),
    ],
    'Karahi': [
      Restaurant(
        name: 'Karahi House',
        specialty: 'Karahi',
        location: 'Saddar, Quetta',
        highlight: 'Tender meat in spicy karahi',
        rating: 4.7,
      ),
      Restaurant(
        name: 'Shahi Karahi',
        specialty: 'Karahi',
        location: 'Kuchlak Road, Quetta',
        highlight: 'Authentic spicy chicken karahi',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Waris Karahi',
        specialty: 'Karahi',
        location: 'Zarghoon Road, Quetta',
        highlight: 'Juicy and flavorful karahi',
        rating: 4.5,
      ),
    ],
    'Pulao': [
      Restaurant(
        name: 'Bismillah Pulao',
        specialty: 'Pulao',
        location: 'Saddar, Quetta',
        highlight: 'Aromatic rice with chicken and beef',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Khyber Pulao',
        specialty: 'Pulao',
        location: 'Jinnah Road, Quetta',
        highlight: 'Special pulao with tender meat',
        rating: 4.4,
      ),
      Restaurant(
        name: 'Shahi Pulao',
        specialty: 'Pulao',
        location: 'Airport Road, Quetta',
        highlight: 'Fluffy rice with flavorful spices',
        rating: 4.3,
      ),
    ],
    'Nihari': [
      Restaurant(
        name: 'Waris Nihari',
        specialty: 'Nihari',
        location: 'Saddar, Quetta',
        highlight: 'Traditional nihari with rich spices',
        rating: 4.6,
      ),
      Restaurant(
        name: 'Shahi Nihari',
        specialty: 'Nihari',
        location: 'Jinnah Road, Quetta',
        highlight: 'Slow-cooked beef nihari',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Quetta Nihari House',
        specialty: 'Nihari',
        location: 'Zarghoon Road, Quetta',
        highlight: 'Classic nihari with rich flavor',
        rating: 4.4,
      ),
    ],
    'Chinese': [
      Restaurant(
        name: 'Golden Dragon',
        specialty: 'Chinese',
        location: 'Saddar, Quetta',
        highlight: 'Traditional Chinese dishes with local spices',
        rating: 4.5,
      ),
      Restaurant(
        name: 'Red Dragon',
        specialty: 'Chinese',
        location: 'Jinnah Road, Quetta',
        highlight: 'Best Chinese food with fresh ingredients',
        rating: 4.6,
      ),
      Restaurant(
        name: 'China Town',
        specialty: 'Chinese',
        location: 'Quetta Cantt',
        highlight: 'Authentic Chinese flavors',
        rating: 4.4,
      ),
    ],
  },
};
